import numpy as np
import matplotlib.pyplot as plt

euler1=np.genfromtxt("eulerdt1.txt")
euler2=np.genfromtxt("eulerdt2.txt")
euler3=np.genfromtxt("eulerdt3.txt")
leapfrog1=np.genfromtxt("leapfrogdt1.txt")
leapfrog2=np.genfromtxt("leapfrogdt2.txt")
leapfrog3=np.genfromtxt("leapfrogdt3.txt")
rk1=np.genfromtxt("rkdt1.txt")
rk2=np.genfromtxt("rkdt2.txt")
rk3=np.genfromtxt("rkdt3.txt")

##################################################################
################Pos
#################################################

plt.figure(figsize=(20,15), dpi=100)
plt.subplot(3,3,1)
plt.plot(euler1[:,3],euler1[:,4],linewidth=0.25)
plt.title("Grafica orbita Tierra, Euler dt=0.002")
plt.subplot(3,3,2)
plt.plot(leapfrog1[:,3],leapfrog1[:,4],c="red",linewidth=0.25)
plt.title("Grafica orbita Tierra, Leapfrog dt=0.002")
plt.subplot(3,3,3)
plt.plot(rk1[:,3],rk1[:,4],c="orange",linewidth=0.25)
plt.title("Grafica orbita Tierra, Rk dt=0.002")

plt.subplot(3,3,4)
plt.plot(euler2[:,3],euler2[:,4],"o--",ms=0.7,linewidth=0.25)
plt.title("Grafica orbita Tierra, Euler dt=0.02")
plt.subplot(3,3,5)
plt.plot(leapfrog2[:,3],leapfrog2[:,4],"o--",ms=0.7, c="red",linewidth=0.25)
plt.title("Grafica orbita Tierra, Leapfrog dt=0.02")
plt.subplot(3,3,6)
plt.plot(rk2[:,3],rk2[:,4],"o--",ms=0.7,c="orange",linewidth=0.25)
plt.title("Grafica orbita Tierra, Rk dt=0.02")

plt.subplot(3,3,7)
plt.plot(euler3[:,3],euler3[:,4],"o--",ms=0.7,linewidth=0.55)
plt.title("Grafica orbita Tierra, Euler dt=0.2")
plt.subplot(3,3,8)
plt.plot(leapfrog3[:,3],leapfrog3[:,4],"o--",ms=0.7, c="red",linewidth=0.55)
plt.title("Grafica orbita Tierra, Leapfrog dt=0.2")
plt.subplot(3,3,9)
plt.plot(rk3[:,3],rk3[:,4],"o--",ms=0.7,c="orange",linewidth=0.55)
plt.title("Grafica orbita Tierra, Rk dt=0.2")
plt.savefig("XY_met_dt.pdf")

######################################################
#############Velocidad
#########################################################

plt.figure(figsize=(20,15), dpi=100)
plt.subplot(3,3,1)
plt.plot(euler1[:,1],euler1[:,2],linewidth=0.25)
plt.title("Grafica velocidad Tierra, Euler dt=0.002")
plt.subplot(3,3,2)
plt.plot(leapfrog1[:,1],leapfrog1[:,2],c="red",linewidth=0.25)
plt.title("Grafica velocidad Tierra, Leapfrog dt=0.002")
plt.subplot(3,3,3)
plt.plot(rk1[:,1],rk1[:,2],c="orange",linewidth=0.25)
plt.title("Grafica velocidad Tierra, Rk dt=0.002")

plt.subplot(3,3,4)
plt.plot(euler2[:,1],euler2[:,2],"o--",ms=0.7,linewidth=0.25)
plt.title("Grafica velocidad Tierra, Euler dt=0.02")
plt.subplot(3,3,5)
plt.plot(leapfrog2[:,1],leapfrog2[:,2], c="red",linewidth=0.25)
plt.title("Grafica velocidad Tierra, Leapfrog dt=0.02")
plt.subplot(3,3,6)
plt.plot(rk2[:,1],rk2[:,2],c="orange",linewidth=0.25)
plt.title("Grafica velocidad Tierra, Rk dt=0.02")

plt.subplot(3,3,7)
plt.plot(euler3[:,1],euler3[:,2],"o--",ms=0.7,linewidth=0.55)
plt.title("Grafica velocidad Tierra, Euler dt=0.2")
plt.subplot(3,3,8)
plt.plot(leapfrog3[:,1],leapfrog3[:,2],"o--",ms=0.7, c="red",linewidth=0.55)
plt.title("Grafica velocidad Tierra, Leapfrog dt=0.2")
plt.subplot(3,3,9)
plt.plot(rk3[:,1],rk3[:,2],"o--",ms=0.7,c="orange",linewidth=0.55)
plt.title("Grafica velocidad Tierra, Rk dt=0.2")
plt.savefig("VxVy_met_dt.pdf")

##############################################
##################Energias
##############################################

plt.figure(figsize=(20,15), dpi=100)
plt.subplot(3,3,1)
plt.plot(euler1[:,0],euler1[:,5],linewidth=2, label="Ec")
plt.plot(euler1[:,0],euler1[:,6],linewidth=2, label="Ep")
plt.plot(euler1[:,0],euler1[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Euler dt=0.002")
plt.subplot(3,3,2)
plt.plot(leapfrog1[:,0],leapfrog1[:,5],linewidth=2, label="Ec")
plt.plot(leapfrog1[:,0],leapfrog1[:,6],linewidth=2, label="Ep")
plt.plot(leapfrog1[:,0],leapfrog1[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Leapfro,2")
plt.subplot(3,3,3)
plt.plot(rk1[:,0],rk1[:,5],linewidth=2, label="Ec")
plt.plot(rk1[:,0],rk1[:,6],linewidth=2, label="Ep")
plt.plot(rk1[:,0],rk1[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Rk dt=0.002")

plt.subplot(3,3,4)
plt.plot(euler2[:,0],euler2[:,5],linewidth=2, label="Ec")
plt.plot(euler2[:,0],euler2[:,6],linewidth=2, label="Ep")
plt.plot(euler2[:,0],euler2[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Euler dt=0.02")
plt.subplot(3,3,5)
plt.plot(leapfrog2[:,0],leapfrog2[:,5],linewidth=2, label="Ec")
plt.plot(leapfrog2[:,0],leapfrog2[:,6],linewidth=2, label="Ep")
plt.plot(leapfrog2[:,0],leapfrog2[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Leapfrog dt=0.02")
plt.subplot(3,3,6)
plt.plot(rk2[:,0],rk2[:,5],linewidth=2, label="Ec")
plt.plot(rk2[:,0],rk2[:,6],linewidth=2, label="Ep")
plt.plot(rk2[:,0],rk2[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Rk dt=0.02")

plt.subplot(3,3,7)
plt.plot(euler3[:,0],euler3[:,5],linewidth=2, label="Ec")
plt.plot(euler3[:,0],euler3[:,6],linewidth=2, label="Ep")
plt.plot(euler3[:,0],euler3[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Euler dt=0.2")
plt.subplot(3,3,8)
plt.plot(leapfrog3[:,0],leapfrog3[:,5],linewidth=2, label="Ec")
plt.plot(leapfrog3[:,0],leapfrog3[:,6],linewidth=2, label="Ep")
plt.plot(leapfrog3[:,0],leapfrog3[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Leapfrog dt=0.2")
plt.subplot(3,3,9)
plt.plot(rk3[:,0],rk3[:,5],linewidth=2, label="Ec")
plt.plot(rk3[:,0],rk3[:,6],linewidth=2, label="Ep")
plt.plot(rk3[:,0],rk3[:,7],linewidth=2, label="Em")
plt.legend()
plt.title("Grafica Energias en Funcion Tiempo, Rk dt=0.2")
plt.savefig("Ener_met_dt.pdf")

###################################
#############Momento
###################################

plt.figure(figsize=(20,15), dpi=100)
plt.subplot(3,3,1)
plt.plot(euler1[:,0],euler1[:,8],linewidth=2, label="Momentox")
plt.plot(euler1[:,0],euler1[:,9],linewidth=2, label="Momentoy")
plt.plot(euler1[:,0],euler1[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Euler dt=0.002")
plt.subplot(3,3,2)
plt.plot(leapfrog1[:,0],leapfrog1[:,8],linewidth=2, label="Mometox")
plt.plot(leapfrog1[:,0],leapfrog1[:,9],linewidth=2, label="Momentoy")
plt.plot(leapfrog1[:,0],leapfrog1[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Leapfrog dt=0.002")
plt.subplot(3,3,3)
plt.plot(rk1[:,0],rk1[:,8],linewidth=2, label="Momentox")
plt.plot(rk1[:,0],rk1[:,9],linewidth=2, label="Momentoy")
plt.plot(rk1[:,0],rk1[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Rk dt=0.002")

plt.subplot(3,3,4)
plt.plot(euler2[:,0],euler2[:,8],linewidth=2, label="Momentox")
plt.plot(euler2[:,0],euler2[:,9],linewidth=2, label="Momentoy")
plt.plot(euler2[:,0],euler2[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Euler dt=0.02")
plt.subplot(3,3,5)
plt.plot(leapfrog2[:,0],leapfrog2[:,8],linewidth=2, label="Momentox")
plt.plot(leapfrog2[:,0],leapfrog2[:,9],linewidth=2, label="Momentoy")
plt.plot(leapfrog2[:,0],leapfrog2[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Leapfrog dt=0.02")
plt.subplot(3,3,6)
plt.plot(rk2[:,0],rk2[:,8],linewidth=2, label="Momentox")
plt.plot(rk2[:,0],rk2[:,9],linewidth=2, label="Momentoy")
plt.plot(rk2[:,0],rk2[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Rk dt=0.02")

plt.subplot(3,3,7)
plt.plot(euler3[:,0],euler3[:,8],linewidth=2, label="Momentox")
plt.plot(euler3[:,0],euler3[:,9],linewidth=2, label="Momentoy")
plt.plot(euler3[:,0],euler3[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Euler dt=0.2")
plt.subplot(3,3,8)
plt.plot(leapfrog3[:,0],leapfrog3[:,8],linewidth=2, label="Momentox")
plt.plot(leapfrog3[:,0],leapfrog3[:,9],linewidth=2, label="Momentoy")
plt.plot(leapfrog3[:,0],leapfrog3[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Leapfrog dt=0.2")
plt.subplot(3,3,9)
plt.plot(rk3[:,0],rk3[:,8],linewidth=2, label="Momentox")
plt.plot(rk3[:,0],rk3[:,9],linewidth=2, label="Momentoy")
plt.plot(rk3[:,0],rk3[:,10],linewidth=2, label="Momento")
plt.legend()
plt.title("Grafica Momento en Funcion Tiempo, Rk dt=0.2")
plt.savefig("Mome_met_dt.pdf")